//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.27 at 05:26:07 PM IST 
//


package com.bornfire.mx.pacs_008_001_08;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClearingChannel2Code__1.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ClearingChannel2Code__1"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="RTGS"/&gt;
 *     &lt;enumeration value="RTNS"/&gt;
 *     &lt;enumeration value="MPNS"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ClearingChannel2Code__1")
@XmlEnum
public enum ClearingChannel2Code1 {


    /**
     * Clearing channel is a real-time gross settlement system.
     * 
     */
    RTGS,

    /**
     * Clearing channel is a real-time net settlement system.
     * 
     */
    RTNS,

    /**
     * Clearing channel is a mass payment net settlement system.
     * 
     */
    MPNS;

    public String value() {
        return name();
    }

    public static ClearingChannel2Code1 fromValue(String v) {
        return valueOf(v);
    }

}
