//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.31 at 10:55:00 AM GST 
//


package com.bornfire.mx.head_001_001_01;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bornfire.jaxb.head_001_001_01 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AppHdr_QNAME = new QName("urn:iso:std:iso:20022:tech:xsd:head.001.001.02", "AppHdr");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bornfire.jaxb.head_001_001_01
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BusinessApplicationHeaderV01 }
     * 
     */
    public BusinessApplicationHeaderV01 createBusinessApplicationHeaderV01() {
        return new BusinessApplicationHeaderV01();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification51 }
     * 
     */
    public BranchAndFinancialInstitutionIdentification51 createBranchAndFinancialInstitutionIdentification51() {
        return new BranchAndFinancialInstitutionIdentification51();
    }

    /**
     * Create an instance of {@link BusinessApplicationHeader11 }
     * 
     */
    public BusinessApplicationHeader11 createBusinessApplicationHeader11() {
        return new BusinessApplicationHeader11();
    }

    /**
     * Create an instance of {@link ClearingSystemMemberIdentification21 }
     * 
     */
    public ClearingSystemMemberIdentification21 createClearingSystemMemberIdentification21() {
        return new ClearingSystemMemberIdentification21();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification81 }
     * 
     */
    public FinancialInstitutionIdentification81 createFinancialInstitutionIdentification81() {
        return new FinancialInstitutionIdentification81();
    }

    /**
     * Create an instance of {@link GenericFinancialIdentification11 }
     * 
     */
    public GenericFinancialIdentification11 createGenericFinancialIdentification11() {
        return new GenericFinancialIdentification11();
    }

    /**
     * Create an instance of {@link Party9Choice1 }
     * 
     */
    public Party9Choice1 createParty9Choice1() {
        return new Party9Choice1();
    }

    /**
     * Create an instance of {@link SignatureEnvelope }
     * 
     */
    public SignatureEnvelope createSignatureEnvelope() {
        return new SignatureEnvelope();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BusinessApplicationHeaderV01 }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BusinessApplicationHeaderV01 }{@code >}
     */
    @XmlElementDecl(namespace = "urn:iso:std:iso:20022:tech:xsd:head.001.001.02", name = "AppHdr")
    public JAXBElement<BusinessApplicationHeaderV01> createAppHdr(BusinessApplicationHeaderV01 value) {
        return new JAXBElement<BusinessApplicationHeaderV01>(_AppHdr_QNAME, BusinessApplicationHeaderV01 .class, null, value);
    }

}
